all:

bin2ascii: Bin2Ascii.cpp
	g++ -Wall Bin2Ascii.cpp -o bin2ascii

dec2hex: Dec2Hex.cpp
	g++ -Wall Dec2Hex.cpp -o dec2hex

input2bin: Input2Bin.cpp
	g++ -Wall Input2Bin.cpp -o input2bin

clean:
	rm bin2ascii dec2hex
